# db_url = jdbc:mysql://localhost:3306/test
db_url = jdbc:mysql://host.docker.internal:3306/test
db_username = root
db_password = Razak@123
# db.url=jdbc:mysql://mysql:3306/patientdb?allowPublicKeyRetrieval=true&useSSL=false
# db.user=patientuser
# db.password=patientpass
